### ISSUE TITLE
Add documentation for log level

### ISSUE THREAD

**Issue by bdurrow** [adfinis-sygroup/foreman-yml#54]
There are a number of configuration options that don't work during import and it is not possible to do a dump from one instance and use the yaml produced unmodified to populate a new instance.  I hope to work on these problems (and ultimately submit a PR) but I don't see a simple way to increase the logging level to DEBUG.  Will you please add this to the documentation?

**Comment by karras** [comment]
Yes, it doesn't cover all settings and resources available in Foreman because you'd need to implement them accordingly. In the long run it might make sense to jump to the official Ansible module `foreman` which is quite generic and maintained by the Foreman project:

http://docs.ansible.com/ansible/latest/modules/foreman_module.html#foreman-module
https://github.com/theforeman/foreman-ansible-modules

AFAIK the log level is currently not exposed or changeable via CLI parameter. IMHO refactoring is required anyway to handle the CLI parameters properly and especially print a better help.

**Comment by bdurrow** [comment]
For anyone viewing this issue, the first link above appears to be a completely different project than the second.  The first comes installed with ansible versions after 2.3 and the second needs to be installed seperately.  The foreman_module installed with ansible is not very useful as of this writing (ansible version 2.5).  It only allows you set the "organization" ([see here)](https://github.com/ansible/ansible/blob/stable-2.5/lib/ansible/modules/remote_management/foreman/foreman.py#L145)

**Comment by karras** [comment]
Yes for now they're two "different" projects. Basically the first implementation of the current `foreman` module is not really useful but just an initial draft I guess.

Have a look at the goals in the README:
https://github.com/theforeman/foreman-ansible-modules#goals

I think it will take some time until these are pushed "upstream" simply because it's maintained mainly by community members.

**Comment by karras** [comment]
Project archived
