### ISSUE TITLE
Overlap with foreman-ansible-modules

### ISSUE THREAD

**Issue by ekohl** [adfinis-sygroup/foreman-yml#71]
https://github.com/theforeman/foreman-ansible-modules intends to achieve pretty much the same as this project. It also upstream supported and uses https://github.com/Apipie/apypie. Are there any thoughts on this?

**Comment by achevalet** [comment]
I would say the benefit of foreman-yml is the dump feature which is really useful if you want to start managing an existing instance with thousands of objects.
I've started to work on the dump feature and was about to do the import, but this part is really redundant with foreman-ansible-modules. So I'm thinking about a new option which would convert foreman-yml results into foreman-ansible-modules compatible files. Thoughts?

**Comment by ekohl** [comment]
@evgeni thoughts on this?

**Comment by evgeni** [comment]
On a mobile, so didn't look too closely, but can't we have a dump module in FAM? Based on the work here and foreman_search_facts which already can dump individual entities.

I know that @nstrug was working on something like that, but don't know the status.

**Comment by evgeni** [comment]
Are you by any chance at cfgmgmtcamp so we can discuss this live?

**Comment by karras** [comment]
Thanks for triggering this discussion! Basically we initiated foreman-yml a few years ago when we had to deploy multiple Foreman instances (Sandpit, Test, Production, etc.) and maintain them. As installing the packages and YML configs with Ansible is only half of the job and hammer-cli relies on IDs we created foreman-yml. Its not super well maintained or written but does the job so far.

A few months back I noticed that you guys started working on an official Ansible module which would be awesome! Please let us know if we can contribute in any way. It would be great to either consolidate foreman-yml into foreman-ansible-modules or move the whole project to the Foreman GitHub organization and combine our efforts. :)

Thoughts?

**Comment by karras** [comment]
@evgeni If you're at the cfgmgmtcamp make sure to have a chat with @erickellerek1, he will actually talk about one of the foreman-yml use cases:

https://cfp.cfgmgmtcamp.be/2020/talk/QNSP9S/

**Comment by evgeni** [comment]
Ah cool, that one was on "to watch" list already. Will definitely join

**Comment by ekohl** [comment]
Was there any discussion and if so, can you share it?

**Comment by evgeni** [comment]
Eric and I met and had a nice chat after his talk.  i think we agreed that ideally foreman-yml would be completely unnecessary and replaced with native foreman tooling (like FAM).

Eric shared an example config which is used to populate Foreman and after a brief look the one thing FAM didn't support was creating "models", and that's been fixed in https://github.com/theforeman/foreman-ansible-modules/pull/700
I still need to go over the example in more detail and check that I didn't miss anything, but pretty confident.

The other feature that exists in foreman-yml is export, and that will require some work on the FAM side, probably in the form of an export role or something. However my understanding was that import is much more important.

Eric please correct me if I misunderstood or misremembering something :)

**Comment by achevalet** [comment]
Thanks for sharing! Personnaly I would love to see that export feature implemented in FAM! 
I think it would address some useful use cases like the bidirectional way of managing foreman objects. Crossed with roles, we could prevent access to sensitive objects and include FAM and merge requests in the process, while users could still update non-sensitive data from UI/API.
Ansible code would be in-sync with manual changes, this could be useful to track changes but also to clone an existing instance of Foreman for backup, DR or testing purpose, with an easy way to filter or modify what is cloned. :)

**Comment by karras** [comment]
Project archived
